-- Table: EAD_STUDENTS
CREATE TABLE EAD_STUDENTS (
      ID INTEGER NOT NULL PRIMARY KEY,
      LEGAL_FNAME VARCHAR(255) NOT NULL,
      LEGAL_LNAME VARCHAR(255) NOT NULL,
      BIRTH_DATE DATE NOT NULL,
      GENDER VARCHAR(1) NOT NULL,
      EMAIL VARCHAR(255) NOT NULL,
      PHONE_NUMBER VARCHAR(255) NOT NULL,
      ADDRESS VARCHAR(255) NOT NULL,
      STUDENT_ID INTEGER NOT NULL UNIQUE,
      CURRENT_PROGRAM VARCHAR(255) NOT NULL,
      START_DATE DATE NOT NULL,
      END_DATE DATE NOT NULL,
      CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UPDATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EAD_STUDENT_ACD_SKILLS (
    STUDENT_ID INTEGER NOT NULL PRIMARY KEY,
    SKILL_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT EAD_STUDENT_ACD_SKILLS_STUDENT_ID_FK FOREIGN KEY (STUDENT_ID) REFERENCES EAD_STUDENTS(STUDENT_ID) ON DELETE CASCADE
);

-- Table: EAD_PROGRAMS
CREATE TABLE EAD_PROGRAMS (
    PROGRAM_CODE VARCHAR(255) NOT NULL PRIMARY KEY,
    PROGRAM_NAME VARCHAR(255) NOT NULL,
    PROGRAM_START_DATE DATE NOT NULL,
    PROGRAM_END_DATE DATE NOT NULL,
    PROGRAM_FEE DECIMAL(10, 2) NOT NULL,
    PROGRAM_PROFESSOR VARCHAR(255) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: EAD_ENROLLMENTS
CREATE TABLE EAD_ENROLLMENTS (
    APPLICATION_ID INTEGER NOT NULL PRIMARY KEY,
    STUDENT_ID INTEGER NOT NULL,
    PROGRAM_CODE VARCHAR(255) NOT NULL,
    PROGRAM_START_DATE DATE NOT NULL,
    AMOUNT_PAID DECIMAL(10, 2) NOT NULL,
    APPLICATION_STATUS VARCHAR(255) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Check Tables
SELECT * FROM EAD_STUDENTS;
SELECT * FROM EAD_PROGRAMS;
SELECT * FROM EAD_ENROLLMENTS;
SELECT * FROM EAD_STUDENTS;

-- Drop Tables
DROP TABLE IF EXISTS EAD_STUDENT_ACD_SKILLS;
DROP TABLE IF EXISTS EAD_PROGRAMS;
DROP TABLE IF EXISTS EAD_ENROLLMENTS;
DROP TABLE IF EXISTS EAD_STUDENTS;